# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-14 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
